"""
USPTO API Client - A Python client library for interacting with the USPTO APIs.

This package provides clients for interacting with both the USPTO Bulk Data API
and the USPTO Patent Data API.
"""

try:
    from ._version import version as __version__  # type: ignore
except ImportError:
    # Package is either not installed in development mode
    # or _version.py was not generated by setuptools_scm
    __version__ = "0.0.0.dev0"

# Import from original locations for backward compatibility
from pyUSPTO.base import (
    BaseUSPTOClient,
)

# Import client implementations from new locations
from pyUSPTO.clients.bulk_data import BulkDataClient
from pyUSPTO.clients.patent_data import PatentDataClient
from pyUSPTO.config import USPTOConfig
from pyUSPTO.exceptions import (
    USPTOApiAuthError,
    USPTOApiError,
    USPTOApiNotFoundError,
    USPTOApiRateLimitError,
)

# Import from original locations for backward compatibility
# These will be replaced with imports from models in the future
from pyUSPTO.models.bulk_data import (
    BulkDataProduct,
    BulkDataResponse,
    FileData,
    ProductFileBag,
)
from pyUSPTO.models.patent_data import (
    PatentDataResponse,
    PatentFileWrapper,
)

__all__ = [
    # Base classes
    "BaseUSPTOClient",
    "USPTOApiError",
    "USPTOApiAuthError",
    "USPTOApiRateLimitError",
    "USPTOApiNotFoundError",
    "USPTOConfig",
    # Bulk Data API
    "BulkDataClient",
    "BulkDataResponse",
    "BulkDataProduct",
    "ProductFileBag",
    "FileData",
    # Patent Data API
    "PatentDataClient",
    "PatentDataResponse",
    "PatentFileWrapper",
]
